### ISSUE TITLE
Setup docker compose

### ISSUE THREAD

**Issue by de-marauder** [de-marauder/aguadolce-backend-assignment#7]
### Tasks
- [x] docker-compose file should include API service, database service and a common network
- [x] Supply environment variables securely
- [x] Write a Dockerfile for API service
